### ISSUE TITLE
Trying to enter "=" crashes the app

### ISSUE THREAD

**Issue by ryonakano** [ryonakano/Spreadsheet#39]
Trying to enter `=` like `=sum(A1, A2)` crashes the app:

```
** (xyz.gelez.spreadsheet:9311): ERROR **: 09:13:13.803: Lexer.vala:46: Unexpected character at 0
Trace/breakpoint trap
```

No error occurs without `=`.

**Comment by Andrewsudarikov** [comment]
Also trying to enter a word in quotes, e.g.: 
`"hello"`
crashes the app.

**Comment by ryonakano** [comment]
> Also trying to enter a word in quotes, e.g.:
> `"hello"`
> crashes the app.

That's a scope of #12.
