### ISSUE TITLE
Missing temporary files (*~) rule in gitignore

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [ryonakano/Spreadsheet#80]
elementary Code creates temporary files (*~) when editing files. I think we should add a rule to gitignore to avoid accidentally adding these files to commits.

**Comment by ryonakano** [comment]
I always use VSCode instead of elementary Code, which does not create those temproary files. :sweat_smile: But we might want to address this issue for developers who use elementary Code since it's the default editor of elementary OS.
